### ISSUE TITLE
Issuance webhook

### ISSUE THREAD

**Issue by waltkb** [walt-id/waltid-identity#572]
like verification webhook

**Comment by alegomes** [comment]
How is it supposed to work?

I've set up a crappy local HTTP server. It works well with requests dispatched from the browser. 

![image](https://github.com/user-attachments/assets/a230c005-374a-44f1-b2b8-d37e4e7b9c94)


However, nothing happens when I call the `/openid4vc/jwt/issue` endpoint with the `statusCallbackUri` header value set...


![image](https://github.com/user-attachments/assets/37e6b6d1-8763-47a3-8ef9-0edf4527cf40)


...or when I claim for the request by using the `/wallet-api/wallet/{wallet}/exchange/useOfferRequest` endpoint.

I mean, the callback endpoint is never called.


![image](https://github.com/user-attachments/assets/70512f03-5739-44db-aa5d-1697c8d31834)


So, I'm not sure if I really understood how does it work.

thanks
